/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_gestion (void)
{
  GtkWidget *gestion;
  GtkWidget *fixed1;
  GtkWidget *test_label;
  GtkWidget *GDPS_actualiser_button;
  GtkWidget *gdps_ajouter;
  GtkWidget *gdps_modifier;
  GtkWidget *gdps_supprimer_button;
  GtkWidget *gdps_chercher_entry;
  GtkWidget *hseparator3;
  GtkWidget *gdps_label10cbs;
  GtkWidget *vseparator2;
  GtkWidget *dsvfbf;
  GtkWidget *scrolledwindow1;
  GtkWidget *treeview;
  GtkWidget *dfbddfn;
  GtkWidget *gdps_stat1_label;
  GtkWidget *gdps_statistique_button;
  GtkWidget *gdps_chercher_button;
  GtkWidget *gdps_msg_erreur;
  GtkWidget *gdps_choixeatb;
  GtkWidget *gdps_stat2_label;
  GtkWidget *gdps_quant_pd;

  gestion = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (gestion), _("window1"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (gestion), fixed1);

  test_label = gtk_label_new ("");
  gtk_widget_show (test_label);
  gtk_fixed_put (GTK_FIXED (fixed1), test_label, 0, 0);
  gtk_widget_set_size_request (test_label, 0, 0);

  GDPS_actualiser_button = gtk_button_new_with_mnemonic (_("Actualiser"));
  gtk_widget_show (GDPS_actualiser_button);
  gtk_fixed_put (GTK_FIXED (fixed1), GDPS_actualiser_button, 872, 72);
  gtk_widget_set_size_request (GDPS_actualiser_button, 128, 40);

  gdps_ajouter = gtk_button_new_with_mnemonic (_("ajouter"));
  gtk_widget_show (gdps_ajouter);
  gtk_fixed_put (GTK_FIXED (fixed1), gdps_ajouter, 872, 128);
  gtk_widget_set_size_request (gdps_ajouter, 128, 40);

  gdps_modifier = gtk_button_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (gdps_modifier);
  gtk_fixed_put (GTK_FIXED (fixed1), gdps_modifier, 872, 184);
  gtk_widget_set_size_request (gdps_modifier, 128, 40);

  gdps_supprimer_button = gtk_button_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (gdps_supprimer_button);
  gtk_fixed_put (GTK_FIXED (fixed1), gdps_supprimer_button, 872, 248);
  gtk_widget_set_size_request (gdps_supprimer_button, 128, 40);

  gdps_chercher_entry = gtk_entry_new ();
  gtk_widget_show (gdps_chercher_entry);
  gtk_fixed_put (GTK_FIXED (fixed1), gdps_chercher_entry, 512, 24);
  gtk_widget_set_size_request (gdps_chercher_entry, 184, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (gdps_chercher_entry), 8226);

  hseparator3 = gtk_hseparator_new ();
  gtk_widget_show (hseparator3);
  gtk_fixed_put (GTK_FIXED (fixed1), hseparator3, 0, 464);
  gtk_widget_set_size_request (hseparator3, 1056, 16);

  gdps_label10cbs = gtk_label_new (_("Le pourcentage des demandes de:"));
  gtk_widget_show (gdps_label10cbs);
  gtk_fixed_put (GTK_FIXED (fixed1), gdps_label10cbs, 24, 376);
  gtk_widget_set_size_request (gdps_label10cbs, 248, 24);

  vseparator2 = gtk_vseparator_new ();
  gtk_widget_show (vseparator2);
  gtk_fixed_put (GTK_FIXED (fixed1), vseparator2, 440, 376);
  gtk_widget_set_size_request (vseparator2, 24, 96);

  dsvfbf = gtk_label_new (_("%"));
  gtk_widget_show (dsvfbf);
  gtk_fixed_put (GTK_FIXED (fixed1), dsvfbf, 240, 424);
  gtk_widget_set_size_request (dsvfbf, 48, 32);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_fixed_put (GTK_FIXED (fixed1), scrolledwindow1, 24, 72);
  gtk_widget_set_size_request (scrolledwindow1, 824, 272);

  treeview = gtk_tree_view_new ();
  gtk_widget_show (treeview);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), treeview);
  gtk_widget_set_size_request (treeview, 768, 272);

  dfbddfn = gtk_label_new (_("Le type de sang le plus demande est:"));
  gtk_widget_show (dfbddfn);
  gtk_fixed_put (GTK_FIXED (fixed1), dfbddfn, 464, 376);
  gtk_widget_set_size_request (dfbddfn, 272, 24);

  gdps_stat1_label = gtk_label_new ("");
  gtk_widget_show (gdps_stat1_label);
  gtk_fixed_put (GTK_FIXED (fixed1), gdps_stat1_label, 136, 424);
  gtk_widget_set_size_request (gdps_stat1_label, 96, 32);

  gdps_statistique_button = gtk_button_new_with_mnemonic (_("Statistique"));
  gtk_widget_show (gdps_statistique_button);
  gtk_fixed_put (GTK_FIXED (fixed1), gdps_statistique_button, 872, 304);
  gtk_widget_set_size_request (gdps_statistique_button, 128, 40);

  gdps_chercher_button = gtk_button_new_with_mnemonic (_("Chercher"));
  gtk_widget_show (gdps_chercher_button);
  gtk_fixed_put (GTK_FIXED (fixed1), gdps_chercher_button, 712, 24);
  gtk_widget_set_size_request (gdps_chercher_button, 88, 32);

  gdps_msg_erreur = gtk_label_new ("");
  gtk_widget_show (gdps_msg_erreur);
  gtk_fixed_put (GTK_FIXED (fixed1), gdps_msg_erreur, 24, 40);
  gtk_widget_set_size_request (gdps_msg_erreur, 432, 24);

  gdps_choixeatb = gtk_combo_box_new_text ();
  gtk_widget_show (gdps_choixeatb);
  gtk_fixed_put (GTK_FIXED (fixed1), gdps_choixeatb, 272, 368);
  gtk_widget_set_size_request (gdps_choixeatb, 168, 32);

  gdps_stat2_label = gtk_label_new ("");
  gtk_widget_show (gdps_stat2_label);
  gtk_fixed_put (GTK_FIXED (fixed1), gdps_stat2_label, 560, 424);
  gtk_widget_set_size_request (gdps_stat2_label, 96, 32);

  gdps_quant_pd = gtk_label_new ("");
  gtk_widget_show (gdps_quant_pd);
  gtk_fixed_put (GTK_FIXED (fixed1), gdps_quant_pd, 672, 424);
  gtk_widget_set_size_request (gdps_quant_pd, 56, 32);

  g_signal_connect ((gpointer) GDPS_actualiser_button, "clicked",
                    G_CALLBACK (on_GDPS_actualiser_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) gdps_ajouter, "clicked",
                    G_CALLBACK (on_gdps_ajouter_clicked),
                    NULL);
  g_signal_connect ((gpointer) gdps_modifier, "clicked",
                    G_CALLBACK (on_gdps_modifier_clicked),
                    NULL);
  g_signal_connect ((gpointer) gdps_supprimer_button, "clicked",
                    G_CALLBACK (on_gdps_supprimer_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) treeview, "row_activated",
                    G_CALLBACK (on_treeview_row_activated),
                    NULL);
  g_signal_connect ((gpointer) gdps_statistique_button, "clicked",
                    G_CALLBACK (on_gdps_statistique_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) gdps_chercher_button, "clicked",
                    G_CALLBACK (on_gdps_chercher_button_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (gestion, gestion, "gestion");
  GLADE_HOOKUP_OBJECT (gestion, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (gestion, test_label, "test_label");
  GLADE_HOOKUP_OBJECT (gestion, GDPS_actualiser_button, "GDPS_actualiser_button");
  GLADE_HOOKUP_OBJECT (gestion, gdps_ajouter, "gdps_ajouter");
  GLADE_HOOKUP_OBJECT (gestion, gdps_modifier, "gdps_modifier");
  GLADE_HOOKUP_OBJECT (gestion, gdps_supprimer_button, "gdps_supprimer_button");
  GLADE_HOOKUP_OBJECT (gestion, gdps_chercher_entry, "gdps_chercher_entry");
  GLADE_HOOKUP_OBJECT (gestion, hseparator3, "hseparator3");
  GLADE_HOOKUP_OBJECT (gestion, gdps_label10cbs, "gdps_label10cbs");
  GLADE_HOOKUP_OBJECT (gestion, vseparator2, "vseparator2");
  GLADE_HOOKUP_OBJECT (gestion, dsvfbf, "dsvfbf");
  GLADE_HOOKUP_OBJECT (gestion, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (gestion, treeview, "treeview");
  GLADE_HOOKUP_OBJECT (gestion, dfbddfn, "dfbddfn");
  GLADE_HOOKUP_OBJECT (gestion, gdps_stat1_label, "gdps_stat1_label");
  GLADE_HOOKUP_OBJECT (gestion, gdps_statistique_button, "gdps_statistique_button");
  GLADE_HOOKUP_OBJECT (gestion, gdps_chercher_button, "gdps_chercher_button");
  GLADE_HOOKUP_OBJECT (gestion, gdps_msg_erreur, "gdps_msg_erreur");
  GLADE_HOOKUP_OBJECT (gestion, gdps_choixeatb, "gdps_choixeatb");
  GLADE_HOOKUP_OBJECT (gestion, gdps_stat2_label, "gdps_stat2_label");
  GLADE_HOOKUP_OBJECT (gestion, gdps_quant_pd, "gdps_quant_pd");

  return gestion;
}

GtkWidget*
create_fenetre_ajouter (void)
{
  GtkWidget *fenetre_ajouter;
  GtkWidget *fixed2;
  GtkWidget *id_etab_label;
  GtkObject *gdps_apos_spin_adj;
  GtkWidget *gdps_apos_spin;
  GtkWidget *gdps_choisir_label;
  GtkObject *gdps_opos_spin_adj;
  GtkWidget *gdps_opos_spin;
  GtkObject *gdps_bpos_spin_adj;
  GtkWidget *gdps_bpos_spin;
  GtkObject *gdps_abpos_spin_adj;
  GtkWidget *gdps_abpos_spin;
  GtkObject *gdps_aneg_spin_adj;
  GtkWidget *gdps_aneg_spin;
  GtkObject *gdps_oneg_spin_adj;
  GtkWidget *gdps_oneg_spin;
  GtkObject *gdps_bneg_spin_adj;
  GtkWidget *gdps_bneg_spin;
  GtkObject *gdps_abneg_spin_adj;
  GtkWidget *gdps_abneg_spin;
  GtkObject *gdps_datelim_jours_spin_adj;
  GtkWidget *gdps_datelim_jours_spin;
  GtkWidget *gdps_datelim_label;
  GtkObject *gdps_datelim_annees_adj;
  GtkWidget *gdps_datelim_annees;
  GtkWidget *gdps_oui_radio;
  GSList *gdps_oui_radio_group = NULL;
  GtkWidget *combobox1;
  GtkWidget *vseparator1;
  GtkWidget *gdps_non_radio;
  GtkWidget *gdps_confirme_label;
  GtkWidget *label1;
  GtkWidget *label2;
  GtkWidget *label3;
  GtkWidget *label4;
  GtkWidget *label5;
  GtkWidget *label6;
  GtkWidget *label7;
  GtkWidget *label8;
  GtkWidget *label9;
  GtkWidget *gdps_datelim_mois_entry;
  GtkWidget *gdps_cm_choix7;
  GtkWidget *gdps_cm_choix6;
  GtkWidget *gdps_cm_choix5;
  GtkWidget *gdps_cm_choix4;
  GtkWidget *gdps_cm_choix3;
  GtkWidget *gdps_cm_choix2;
  GtkWidget *gdps_cm_choix1;
  GtkWidget *gdps_cm_choix8;
  GtkWidget *hseparator1;
  GtkWidget *gdps_ajouter_button;
  GtkWidget *gdps_msg_conf;

  fenetre_ajouter = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (fenetre_ajouter), _("window1"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (fenetre_ajouter), fixed2);

  id_etab_label = gtk_label_new (_("Etablissement"));
  gtk_widget_show (id_etab_label);
  gtk_fixed_put (GTK_FIXED (fixed2), id_etab_label, 8, 24);
  gtk_widget_set_size_request (id_etab_label, 128, 24);

  gdps_apos_spin_adj = gtk_adjustment_new (0, 0, 100, 1, 10, 10);
  gdps_apos_spin = gtk_spin_button_new (GTK_ADJUSTMENT (gdps_apos_spin_adj), 1, 0);
  gtk_widget_show (gdps_apos_spin);
  gtk_fixed_put (GTK_FIXED (fixed2), gdps_apos_spin, 192, 104);
  gtk_widget_set_size_request (gdps_apos_spin, 48, 24);

  gdps_choisir_label = gtk_label_new (_("Choisir le type de sang\net sa capacit\303\251:"));
  gtk_widget_show (gdps_choisir_label);
  gtk_fixed_put (GTK_FIXED (fixed2), gdps_choisir_label, 8, 80);
  gtk_widget_set_size_request (gdps_choisir_label, 176, 40);

  gdps_opos_spin_adj = gtk_adjustment_new (0, 0, 100, 1, 10, 10);
  gdps_opos_spin = gtk_spin_button_new (GTK_ADJUSTMENT (gdps_opos_spin_adj), 1, 0);
  gtk_widget_show (gdps_opos_spin);
  gtk_fixed_put (GTK_FIXED (fixed2), gdps_opos_spin, 192, 168);
  gtk_widget_set_size_request (gdps_opos_spin, 48, 24);

  gdps_bpos_spin_adj = gtk_adjustment_new (0, 0, 100, 1, 10, 10);
  gdps_bpos_spin = gtk_spin_button_new (GTK_ADJUSTMENT (gdps_bpos_spin_adj), 1, 0);
  gtk_widget_show (gdps_bpos_spin);
  gtk_fixed_put (GTK_FIXED (fixed2), gdps_bpos_spin, 192, 232);
  gtk_widget_set_size_request (gdps_bpos_spin, 48, 24);

  gdps_abpos_spin_adj = gtk_adjustment_new (0, 0, 100, 1, 10, 10);
  gdps_abpos_spin = gtk_spin_button_new (GTK_ADJUSTMENT (gdps_abpos_spin_adj), 1, 0);
  gtk_widget_show (gdps_abpos_spin);
  gtk_fixed_put (GTK_FIXED (fixed2), gdps_abpos_spin, 192, 296);
  gtk_widget_set_size_request (gdps_abpos_spin, 48, 24);

  gdps_aneg_spin_adj = gtk_adjustment_new (0, 0, 100, 1, 10, 10);
  gdps_aneg_spin = gtk_spin_button_new (GTK_ADJUSTMENT (gdps_aneg_spin_adj), 1, 0);
  gtk_widget_show (gdps_aneg_spin);
  gtk_fixed_put (GTK_FIXED (fixed2), gdps_aneg_spin, 312, 104);
  gtk_widget_set_size_request (gdps_aneg_spin, 48, 24);

  gdps_oneg_spin_adj = gtk_adjustment_new (0, 0, 100, 1, 10, 10);
  gdps_oneg_spin = gtk_spin_button_new (GTK_ADJUSTMENT (gdps_oneg_spin_adj), 1, 0);
  gtk_widget_show (gdps_oneg_spin);
  gtk_fixed_put (GTK_FIXED (fixed2), gdps_oneg_spin, 312, 168);
  gtk_widget_set_size_request (gdps_oneg_spin, 48, 24);

  gdps_bneg_spin_adj = gtk_adjustment_new (0, 0, 100, 1, 10, 10);
  gdps_bneg_spin = gtk_spin_button_new (GTK_ADJUSTMENT (gdps_bneg_spin_adj), 1, 0);
  gtk_widget_show (gdps_bneg_spin);
  gtk_fixed_put (GTK_FIXED (fixed2), gdps_bneg_spin, 312, 232);
  gtk_widget_set_size_request (gdps_bneg_spin, 48, 24);

  gdps_abneg_spin_adj = gtk_adjustment_new (0, 0, 100, 1, 10, 10);
  gdps_abneg_spin = gtk_spin_button_new (GTK_ADJUSTMENT (gdps_abneg_spin_adj), 1, 0);
  gtk_widget_show (gdps_abneg_spin);
  gtk_fixed_put (GTK_FIXED (fixed2), gdps_abneg_spin, 312, 296);
  gtk_widget_set_size_request (gdps_abneg_spin, 48, 24);

  gdps_datelim_jours_spin_adj = gtk_adjustment_new (0, 0, 31, 1, 10, 10);
  gdps_datelim_jours_spin = gtk_spin_button_new (GTK_ADJUSTMENT (gdps_datelim_jours_spin_adj), 1, 0);
  gtk_widget_show (gdps_datelim_jours_spin);
  gtk_fixed_put (GTK_FIXED (fixed2), gdps_datelim_jours_spin, 136, 344);
  gtk_widget_set_size_request (gdps_datelim_jours_spin, 60, 27);

  gdps_datelim_label = gtk_label_new (_("Date Limtite:"));
  gtk_widget_show (gdps_datelim_label);
  gtk_fixed_put (GTK_FIXED (fixed2), gdps_datelim_label, 16, 344);
  gtk_widget_set_size_request (gdps_datelim_label, 104, 24);

  gdps_datelim_annees_adj = gtk_adjustment_new (2023, 1800, 2030, 1, 10, 10);
  gdps_datelim_annees = gtk_spin_button_new (GTK_ADJUSTMENT (gdps_datelim_annees_adj), 1, 0);
  gtk_widget_show (gdps_datelim_annees);
  gtk_fixed_put (GTK_FIXED (fixed2), gdps_datelim_annees, 304, 344);
  gtk_widget_set_size_request (gdps_datelim_annees, 60, 27);

  gdps_oui_radio = gtk_radio_button_new_with_mnemonic (NULL, _("Oui"));
  gtk_widget_show (gdps_oui_radio);
  gtk_fixed_put (GTK_FIXED (fixed2), gdps_oui_radio, 224, 408);
  gtk_widget_set_size_request (gdps_oui_radio, 64, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (gdps_oui_radio), gdps_oui_radio_group);
  gdps_oui_radio_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (gdps_oui_radio));

  combobox1 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox1);
  gtk_fixed_put (GTK_FIXED (fixed2), combobox1, 144, 16);
  gtk_widget_set_size_request (combobox1, 136, 32);

  vseparator1 = gtk_vseparator_new ();
  gtk_widget_show (vseparator1);
  gtk_fixed_put (GTK_FIXED (fixed2), vseparator1, 384, 16);
  gtk_widget_set_size_request (vseparator1, 16, 368);

  gdps_non_radio = gtk_radio_button_new_with_mnemonic (NULL, _("Non"));
  gtk_widget_show (gdps_non_radio);
  gtk_fixed_put (GTK_FIXED (fixed2), gdps_non_radio, 312, 408);
  gtk_widget_set_size_request (gdps_non_radio, 72, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (gdps_non_radio), gdps_oui_radio_group);
  gdps_oui_radio_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (gdps_non_radio));

  gdps_confirme_label = gtk_label_new (_("Vous confirmer votre choix?"));
  gtk_widget_show (gdps_confirme_label);
  gtk_fixed_put (GTK_FIXED (fixed2), gdps_confirme_label, 16, 408);
  gtk_widget_set_size_request (gdps_confirme_label, 192, 24);

  label1 = gtk_label_new (_("Conditions medical:"));
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed2), label1, 408, 24);
  gtk_widget_set_size_request (label1, 152, 24);

  label2 = gtk_label_new (_("A+:"));
  gtk_widget_show (label2);
  gtk_fixed_put (GTK_FIXED (fixed2), label2, 192, 80);
  gtk_widget_set_size_request (label2, 41, 17);

  label3 = gtk_label_new (_("O+:"));
  gtk_widget_show (label3);
  gtk_fixed_put (GTK_FIXED (fixed2), label3, 192, 144);
  gtk_widget_set_size_request (label3, 41, 17);

  label4 = gtk_label_new (_("B+:"));
  gtk_widget_show (label4);
  gtk_fixed_put (GTK_FIXED (fixed2), label4, 192, 208);
  gtk_widget_set_size_request (label4, 41, 17);

  label5 = gtk_label_new (_("AB+:"));
  gtk_widget_show (label5);
  gtk_fixed_put (GTK_FIXED (fixed2), label5, 192, 272);
  gtk_widget_set_size_request (label5, 41, 17);

  label6 = gtk_label_new (_("A-:"));
  gtk_widget_show (label6);
  gtk_fixed_put (GTK_FIXED (fixed2), label6, 312, 80);
  gtk_widget_set_size_request (label6, 41, 17);

  label7 = gtk_label_new (_("O-:"));
  gtk_widget_show (label7);
  gtk_fixed_put (GTK_FIXED (fixed2), label7, 312, 144);
  gtk_widget_set_size_request (label7, 41, 17);

  label8 = gtk_label_new (_("B-:"));
  gtk_widget_show (label8);
  gtk_fixed_put (GTK_FIXED (fixed2), label8, 312, 208);
  gtk_widget_set_size_request (label8, 41, 17);

  label9 = gtk_label_new (_("AB-:"));
  gtk_widget_show (label9);
  gtk_fixed_put (GTK_FIXED (fixed2), label9, 312, 272);
  gtk_widget_set_size_request (label9, 41, 17);

  gdps_datelim_mois_entry = gtk_combo_box_new_text ();
  gtk_widget_show (gdps_datelim_mois_entry);
  gtk_fixed_put (GTK_FIXED (fixed2), gdps_datelim_mois_entry, 200, 344);
  gtk_widget_set_size_request (gdps_datelim_mois_entry, 96, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (gdps_datelim_mois_entry), _("Janvier"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (gdps_datelim_mois_entry), _("Fevrier"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (gdps_datelim_mois_entry), _("Mars"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (gdps_datelim_mois_entry), _("Avril"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (gdps_datelim_mois_entry), _("Mai"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (gdps_datelim_mois_entry), _("Juin"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (gdps_datelim_mois_entry), _("Juilliet"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (gdps_datelim_mois_entry), _("Aout"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (gdps_datelim_mois_entry), _("Septembre"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (gdps_datelim_mois_entry), _("Otobre"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (gdps_datelim_mois_entry), _("Novembre"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (gdps_datelim_mois_entry), _("Decembre"));

  gdps_cm_choix7 = gtk_check_button_new_with_mnemonic (_("H\303\251morragie interne"));
  gtk_widget_show (gdps_cm_choix7);
  gtk_fixed_put (GTK_FIXED (fixed2), gdps_cm_choix7, 416, 304);
  gtk_widget_set_size_request (gdps_cm_choix7, 176, 24);

  gdps_cm_choix6 = gtk_check_button_new_with_mnemonic (_("Interventions cardiaques"));
  gtk_widget_show (gdps_cm_choix6);
  gtk_fixed_put (GTK_FIXED (fixed2), gdps_cm_choix6, 416, 264);
  gtk_widget_set_size_request (gdps_cm_choix6, 208, 24);

  gdps_cm_choix5 = gtk_check_button_new_with_mnemonic (_("Cancers"));
  gtk_widget_show (gdps_cm_choix5);
  gtk_fixed_put (GTK_FIXED (fixed2), gdps_cm_choix5, 416, 224);
  gtk_widget_set_size_request (gdps_cm_choix5, 152, 24);

  gdps_cm_choix4 = gtk_check_button_new_with_mnemonic (_("Maladies du sang"));
  gtk_widget_show (gdps_cm_choix4);
  gtk_fixed_put (GTK_FIXED (fixed2), gdps_cm_choix4, 416, 184);
  gtk_widget_set_size_request (gdps_cm_choix4, 152, 24);

  gdps_cm_choix3 = gtk_check_button_new_with_mnemonic (_("An\303\251mie S\303\251v\303\250re"));
  gtk_widget_show (gdps_cm_choix3);
  gtk_fixed_put (GTK_FIXED (fixed2), gdps_cm_choix3, 416, 144);
  gtk_widget_set_size_request (gdps_cm_choix3, 136, 24);

  gdps_cm_choix2 = gtk_check_button_new_with_mnemonic (_("Traumatisme"));
  gtk_widget_show (gdps_cm_choix2);
  gtk_fixed_put (GTK_FIXED (fixed2), gdps_cm_choix2, 416, 104);
  gtk_widget_set_size_request (gdps_cm_choix2, 112, 24);

  gdps_cm_choix1 = gtk_check_button_new_with_mnemonic (_("Chirurgie"));
  gtk_widget_show (gdps_cm_choix1);
  gtk_fixed_put (GTK_FIXED (fixed2), gdps_cm_choix1, 416, 64);
  gtk_widget_set_size_request (gdps_cm_choix1, 112, 32);

  gdps_cm_choix8 = gtk_check_button_new_with_mnemonic (_("Complications pendant la grossesse"));
  gtk_widget_show (gdps_cm_choix8);
  gtk_fixed_put (GTK_FIXED (fixed2), gdps_cm_choix8, 416, 344);
  gtk_widget_set_size_request (gdps_cm_choix8, 280, 24);

  hseparator1 = gtk_hseparator_new ();
  gtk_widget_show (hseparator1);
  gtk_fixed_put (GTK_FIXED (fixed2), hseparator1, 0, 480);
  gtk_widget_set_size_request (hseparator1, 720, 16);

  gdps_ajouter_button = gtk_button_new_with_mnemonic (_("Ajouter la demande"));
  gtk_widget_show (gdps_ajouter_button);
  gtk_fixed_put (GTK_FIXED (fixed2), gdps_ajouter_button, 480, 432);
  gtk_widget_set_size_request (gdps_ajouter_button, 160, 48);

  gdps_msg_conf = gtk_label_new ("");
  gtk_widget_show (gdps_msg_conf);
  gtk_fixed_put (GTK_FIXED (fixed2), gdps_msg_conf, 16, 440);
  gtk_widget_set_size_request (gdps_msg_conf, 320, 25);

  g_signal_connect ((gpointer) gdps_oui_radio, "toggled",
                    G_CALLBACK (on_gdps_oui_radio_toggled),
                    NULL);
  g_signal_connect ((gpointer) gdps_non_radio, "toggled",
                    G_CALLBACK (on_gdps_non_radio_toggled),
                    NULL);
  g_signal_connect ((gpointer) gdps_cm_choix7, "toggled",
                    G_CALLBACK (on_gdps_cm_choix7_toggled),
                    NULL);
  g_signal_connect ((gpointer) gdps_cm_choix6, "toggled",
                    G_CALLBACK (on_gdps_cm_choix6_toggled),
                    NULL);
  g_signal_connect ((gpointer) gdps_cm_choix5, "toggled",
                    G_CALLBACK (on_gdps_cm_choix5_toggled),
                    NULL);
  g_signal_connect ((gpointer) gdps_cm_choix4, "toggled",
                    G_CALLBACK (on_gdps_cm_choix4_toggled),
                    NULL);
  g_signal_connect ((gpointer) gdps_cm_choix3, "toggled",
                    G_CALLBACK (on_gdps_cm_choix3_toggled),
                    NULL);
  g_signal_connect ((gpointer) gdps_cm_choix2, "toggled",
                    G_CALLBACK (on_gdps_cm_choix2_toggled),
                    NULL);
  g_signal_connect ((gpointer) gdps_cm_choix1, "toggled",
                    G_CALLBACK (on_gdps_cm_choix1_toggled),
                    NULL);
  g_signal_connect ((gpointer) gdps_cm_choix8, "toggled",
                    G_CALLBACK (on_gdps_cm_choix8_toggled),
                    NULL);
  g_signal_connect ((gpointer) gdps_ajouter_button, "clicked",
                    G_CALLBACK (on_gdps_ajouter_button_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (fenetre_ajouter, fenetre_ajouter, "fenetre_ajouter");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, id_etab_label, "id_etab_label");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, gdps_apos_spin, "gdps_apos_spin");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, gdps_choisir_label, "gdps_choisir_label");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, gdps_opos_spin, "gdps_opos_spin");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, gdps_bpos_spin, "gdps_bpos_spin");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, gdps_abpos_spin, "gdps_abpos_spin");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, gdps_aneg_spin, "gdps_aneg_spin");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, gdps_oneg_spin, "gdps_oneg_spin");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, gdps_bneg_spin, "gdps_bneg_spin");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, gdps_abneg_spin, "gdps_abneg_spin");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, gdps_datelim_jours_spin, "gdps_datelim_jours_spin");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, gdps_datelim_label, "gdps_datelim_label");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, gdps_datelim_annees, "gdps_datelim_annees");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, gdps_oui_radio, "gdps_oui_radio");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, combobox1, "combobox1");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, vseparator1, "vseparator1");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, gdps_non_radio, "gdps_non_radio");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, gdps_confirme_label, "gdps_confirme_label");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, label1, "label1");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, label2, "label2");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, label3, "label3");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, label4, "label4");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, label5, "label5");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, label6, "label6");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, label7, "label7");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, label8, "label8");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, label9, "label9");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, gdps_datelim_mois_entry, "gdps_datelim_mois_entry");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, gdps_cm_choix7, "gdps_cm_choix7");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, gdps_cm_choix6, "gdps_cm_choix6");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, gdps_cm_choix5, "gdps_cm_choix5");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, gdps_cm_choix4, "gdps_cm_choix4");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, gdps_cm_choix3, "gdps_cm_choix3");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, gdps_cm_choix2, "gdps_cm_choix2");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, gdps_cm_choix1, "gdps_cm_choix1");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, gdps_cm_choix8, "gdps_cm_choix8");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, hseparator1, "hseparator1");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, gdps_ajouter_button, "gdps_ajouter_button");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, gdps_msg_conf, "gdps_msg_conf");

  return fenetre_ajouter;
}

GtkWidget*
create_fenetre_modifier (void)
{
  GtkWidget *fenetre_modifier;
  GtkWidget *fixed3;
  GtkObject *gdps_modif_apos_adj;
  GtkWidget *gdps_modif_apos;
  GtkObject *gdps_modif_aneg_adj;
  GtkWidget *gdps_modif_aneg;
  GtkObject *gdps_modif_opos_adj;
  GtkWidget *gdps_modif_opos;
  GtkObject *gdps_modif_oneg_adj;
  GtkWidget *gdps_modif_oneg;
  GtkObject *gdps_modif_bpos_adj;
  GtkWidget *gdps_modif_bpos;
  GtkObject *gdps_modif_bneg_adj;
  GtkWidget *gdps_modif_bneg;
  GtkObject *gdps_modif_abpos_adj;
  GtkWidget *gdps_modif_abpos;
  GtkObject *gdps_modif_abneg_adj;
  GtkWidget *gdps_modif_abneg;
  GtkWidget *gdps_modif_aneg_label;
  GtkWidget *gdps_modif_label18;
  GtkWidget *gdps_modif_label20;
  GtkWidget *gdps_modif_label22;
  GtkWidget *gdps_modif_label17;
  GtkWidget *gdps_modif_label19;
  GtkWidget *gdps_modif_label21;
  GtkWidget *gdps_modif_iddem_label;
  GtkWidget *gdps_modif_idetab_label;
  GtkWidget *gdps_modi_label14;
  GtkWidget *hseparator2;
  GtkWidget *gdps_modifer_button;
  GtkWidget *gdps_modif_iddem_sortie;
  GtkWidget *gdps_modif_oui;
  GSList *gdps_modif_oui_group = NULL;
  GtkWidget *gdps_modif_non;
  GtkWidget *gdps_modif_choix1;
  GtkWidget *gdps_modif_choix2;
  GtkWidget *gdps_modif_choix4;
  GtkWidget *gdps_modif_choix5;
  GtkWidget *gdps_modif_choix6;
  GtkWidget *gdps_modif_choix7;
  GtkWidget *gdps_modif_choix8;
  GtkWidget *gdps_modif_label15;
  GtkWidget *gdps_modif_choix3;
  GtkWidget *gdps_modif_label24;
  GtkWidget *gdps_modif_msg_conf;
  GtkWidget *gdps_modif_label23;
  GtkWidget *gdps_modif_idetab_sortie;
  GtkWidget *gdps_opos_old;
  GtkWidget *gdps_apos_old;
  GtkWidget *gdps_bpos_old;
  GtkWidget *gdps_abpos_old;
  GtkWidget *gdps_aneg_old;
  GtkWidget *gdps_oneg_old;
  GtkWidget *gdps_bneg_old;
  GtkWidget *gdps_abneg_old;

  fenetre_modifier = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_container_set_border_width (GTK_CONTAINER (fenetre_modifier), 3);
  gtk_window_set_title (GTK_WINDOW (fenetre_modifier), _("window1"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (fenetre_modifier), fixed3);

  gdps_modif_apos_adj = gtk_adjustment_new (0, 0, 100, 1, 10, 10);
  gdps_modif_apos = gtk_spin_button_new (GTK_ADJUSTMENT (gdps_modif_apos_adj), 1, 0);
  gtk_widget_show (gdps_modif_apos);
  gtk_fixed_put (GTK_FIXED (fixed3), gdps_modif_apos, 232, 120);
  gtk_widget_set_size_request (gdps_modif_apos, 48, 24);

  gdps_modif_aneg_adj = gtk_adjustment_new (0, 0, 100, 1, 10, 10);
  gdps_modif_aneg = gtk_spin_button_new (GTK_ADJUSTMENT (gdps_modif_aneg_adj), 1, 0);
  gtk_widget_show (gdps_modif_aneg);
  gtk_fixed_put (GTK_FIXED (fixed3), gdps_modif_aneg, 336, 120);
  gtk_widget_set_size_request (gdps_modif_aneg, 48, 24);

  gdps_modif_opos_adj = gtk_adjustment_new (0, 0, 100, 1, 10, 10);
  gdps_modif_opos = gtk_spin_button_new (GTK_ADJUSTMENT (gdps_modif_opos_adj), 1, 0);
  gtk_widget_show (gdps_modif_opos);
  gtk_fixed_put (GTK_FIXED (fixed3), gdps_modif_opos, 232, 184);
  gtk_widget_set_size_request (gdps_modif_opos, 48, 24);

  gdps_modif_oneg_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  gdps_modif_oneg = gtk_spin_button_new (GTK_ADJUSTMENT (gdps_modif_oneg_adj), 1, 0);
  gtk_widget_show (gdps_modif_oneg);
  gtk_fixed_put (GTK_FIXED (fixed3), gdps_modif_oneg, 336, 184);
  gtk_widget_set_size_request (gdps_modif_oneg, 48, 24);

  gdps_modif_bpos_adj = gtk_adjustment_new (0, 0, 100, 1, 10, 10);
  gdps_modif_bpos = gtk_spin_button_new (GTK_ADJUSTMENT (gdps_modif_bpos_adj), 1, 0);
  gtk_widget_show (gdps_modif_bpos);
  gtk_fixed_put (GTK_FIXED (fixed3), gdps_modif_bpos, 232, 248);
  gtk_widget_set_size_request (gdps_modif_bpos, 48, 24);

  gdps_modif_bneg_adj = gtk_adjustment_new (0, 0, 100, 1, 10, 10);
  gdps_modif_bneg = gtk_spin_button_new (GTK_ADJUSTMENT (gdps_modif_bneg_adj), 1, 0);
  gtk_widget_show (gdps_modif_bneg);
  gtk_fixed_put (GTK_FIXED (fixed3), gdps_modif_bneg, 336, 248);
  gtk_widget_set_size_request (gdps_modif_bneg, 48, 24);

  gdps_modif_abpos_adj = gtk_adjustment_new (0, 0, 100, 1, 10, 10);
  gdps_modif_abpos = gtk_spin_button_new (GTK_ADJUSTMENT (gdps_modif_abpos_adj), 1, 0);
  gtk_widget_show (gdps_modif_abpos);
  gtk_fixed_put (GTK_FIXED (fixed3), gdps_modif_abpos, 232, 312);
  gtk_widget_set_size_request (gdps_modif_abpos, 48, 24);

  gdps_modif_abneg_adj = gtk_adjustment_new (0, 0, 100, 1, 10, 10);
  gdps_modif_abneg = gtk_spin_button_new (GTK_ADJUSTMENT (gdps_modif_abneg_adj), 1, 0);
  gtk_widget_show (gdps_modif_abneg);
  gtk_fixed_put (GTK_FIXED (fixed3), gdps_modif_abneg, 336, 312);
  gtk_widget_set_size_request (gdps_modif_abneg, 48, 24);

  gdps_modif_aneg_label = gtk_label_new (_("A-:"));
  gtk_widget_show (gdps_modif_aneg_label);
  gtk_fixed_put (GTK_FIXED (fixed3), gdps_modif_aneg_label, 328, 96);
  gtk_widget_set_size_request (gdps_modif_aneg_label, 32, 24);

  gdps_modif_label18 = gtk_label_new (_("O-:"));
  gtk_widget_show (gdps_modif_label18);
  gtk_fixed_put (GTK_FIXED (fixed3), gdps_modif_label18, 328, 160);
  gtk_widget_set_size_request (gdps_modif_label18, 32, 24);

  gdps_modif_label20 = gtk_label_new (_("B-:"));
  gtk_widget_show (gdps_modif_label20);
  gtk_fixed_put (GTK_FIXED (fixed3), gdps_modif_label20, 328, 224);
  gtk_widget_set_size_request (gdps_modif_label20, 32, 24);

  gdps_modif_label22 = gtk_label_new (_("AB-:"));
  gtk_widget_show (gdps_modif_label22);
  gtk_fixed_put (GTK_FIXED (fixed3), gdps_modif_label22, 320, 288);
  gtk_widget_set_size_request (gdps_modif_label22, 48, 24);

  gdps_modif_label17 = gtk_label_new (_("O+:"));
  gtk_widget_show (gdps_modif_label17);
  gtk_fixed_put (GTK_FIXED (fixed3), gdps_modif_label17, 224, 160);
  gtk_widget_set_size_request (gdps_modif_label17, 40, 24);

  gdps_modif_label19 = gtk_label_new (_("B+:"));
  gtk_widget_show (gdps_modif_label19);
  gtk_fixed_put (GTK_FIXED (fixed3), gdps_modif_label19, 224, 224);
  gtk_widget_set_size_request (gdps_modif_label19, 40, 24);

  gdps_modif_label21 = gtk_label_new (_("AB+:"));
  gtk_widget_show (gdps_modif_label21);
  gtk_fixed_put (GTK_FIXED (fixed3), gdps_modif_label21, 224, 288);
  gtk_widget_set_size_request (gdps_modif_label21, 40, 24);

  gdps_modif_iddem_label = gtk_label_new (_("ID demande: "));
  gtk_widget_show (gdps_modif_iddem_label);
  gtk_fixed_put (GTK_FIXED (fixed3), gdps_modif_iddem_label, 80, 16);
  gtk_widget_set_size_request (gdps_modif_iddem_label, 152, 24);

  gdps_modif_idetab_label = gtk_label_new (_("Etablissement demandeur: "));
  gtk_widget_show (gdps_modif_idetab_label);
  gtk_fixed_put (GTK_FIXED (fixed3), gdps_modif_idetab_label, 8, 48);
  gtk_widget_set_size_request (gdps_modif_idetab_label, 200, 24);

  gdps_modi_label14 = gtk_label_new (_("Sang demand\303\251/ Quantite:"));
  gtk_widget_show (gdps_modi_label14);
  gtk_fixed_put (GTK_FIXED (fixed3), gdps_modi_label14, 8, 96);
  gtk_widget_set_size_request (gdps_modi_label14, 192, 24);

  hseparator2 = gtk_hseparator_new ();
  gtk_widget_show (hseparator2);
  gtk_fixed_put (GTK_FIXED (fixed3), hseparator2, -8, 368);
  gtk_widget_set_size_request (hseparator2, 736, 16);

  gdps_modifer_button = gtk_button_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (gdps_modifer_button);
  gtk_fixed_put (GTK_FIXED (fixed3), gdps_modifer_button, 464, 400);
  gtk_widget_set_size_request (gdps_modifer_button, 176, 40);

  gdps_modif_iddem_sortie = gtk_label_new (_("label11"));
  gtk_widget_show (gdps_modif_iddem_sortie);
  gtk_fixed_put (GTK_FIXED (fixed3), gdps_modif_iddem_sortie, 208, 16);
  gtk_widget_set_size_request (gdps_modif_iddem_sortie, 176, 24);

  gdps_modif_oui = gtk_radio_button_new_with_mnemonic (NULL, _("oui"));
  gtk_widget_show (gdps_modif_oui);
  gtk_fixed_put (GTK_FIXED (fixed3), gdps_modif_oui, 64, 416);
  gtk_widget_set_size_request (gdps_modif_oui, 88, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (gdps_modif_oui), gdps_modif_oui_group);
  gdps_modif_oui_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (gdps_modif_oui));

  gdps_modif_non = gtk_radio_button_new_with_mnemonic (NULL, _("non"));
  gtk_widget_show (gdps_modif_non);
  gtk_fixed_put (GTK_FIXED (fixed3), gdps_modif_non, 168, 416);
  gtk_widget_set_size_request (gdps_modif_non, 96, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (gdps_modif_non), gdps_modif_oui_group);
  gdps_modif_oui_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (gdps_modif_non));

  gdps_modif_choix1 = gtk_check_button_new_with_mnemonic (_("Chirurgie"));
  gtk_widget_show (gdps_modif_choix1);
  gtk_fixed_put (GTK_FIXED (fixed3), gdps_modif_choix1, 440, 88);
  gtk_widget_set_size_request (gdps_modif_choix1, 224, 24);

  gdps_modif_choix2 = gtk_check_button_new_with_mnemonic (_("Traumatisme"));
  gtk_widget_show (gdps_modif_choix2);
  gtk_fixed_put (GTK_FIXED (fixed3), gdps_modif_choix2, 440, 120);
  gtk_widget_set_size_request (gdps_modif_choix2, 208, 24);

  gdps_modif_choix4 = gtk_check_button_new_with_mnemonic (_("Maladie du sang"));
  gtk_widget_show (gdps_modif_choix4);
  gtk_fixed_put (GTK_FIXED (fixed3), gdps_modif_choix4, 440, 184);
  gtk_widget_set_size_request (gdps_modif_choix4, 216, 24);

  gdps_modif_choix5 = gtk_check_button_new_with_mnemonic (_("Cansers"));
  gtk_widget_show (gdps_modif_choix5);
  gtk_fixed_put (GTK_FIXED (fixed3), gdps_modif_choix5, 440, 216);
  gtk_widget_set_size_request (gdps_modif_choix5, 208, 24);

  gdps_modif_choix6 = gtk_check_button_new_with_mnemonic (_("Intervention cardiaque"));
  gtk_widget_show (gdps_modif_choix6);
  gtk_fixed_put (GTK_FIXED (fixed3), gdps_modif_choix6, 440, 248);
  gtk_widget_set_size_request (gdps_modif_choix6, 224, 24);

  gdps_modif_choix7 = gtk_check_button_new_with_mnemonic (_("Hemorragie interne"));
  gtk_widget_show (gdps_modif_choix7);
  gtk_fixed_put (GTK_FIXED (fixed3), gdps_modif_choix7, 440, 280);
  gtk_widget_set_size_request (gdps_modif_choix7, 192, 24);

  gdps_modif_choix8 = gtk_check_button_new_with_mnemonic (_("Complication peandant la grossesse"));
  gtk_widget_show (gdps_modif_choix8);
  gtk_fixed_put (GTK_FIXED (fixed3), gdps_modif_choix8, 440, 312);
  gtk_widget_set_size_request (gdps_modif_choix8, 280, 24);

  gdps_modif_label15 = gtk_label_new (_("A+:"));
  gtk_widget_show (gdps_modif_label15);
  gtk_fixed_put (GTK_FIXED (fixed3), gdps_modif_label15, 224, 96);
  gtk_widget_set_size_request (gdps_modif_label15, 40, 24);

  gdps_modif_choix3 = gtk_check_button_new_with_mnemonic (_("Anemie severe"));
  gtk_widget_show (gdps_modif_choix3);
  gtk_fixed_put (GTK_FIXED (fixed3), gdps_modif_choix3, 440, 152);
  gtk_widget_set_size_request (gdps_modif_choix3, 216, 24);

  gdps_modif_label24 = gtk_label_new (_("Vous confirmer votre choix?"));
  gtk_widget_show (gdps_modif_label24);
  gtk_fixed_put (GTK_FIXED (fixed3), gdps_modif_label24, 8, 384);
  gtk_widget_set_size_request (gdps_modif_label24, 208, 24);

  gdps_modif_msg_conf = gtk_label_new ("");
  gtk_widget_show (gdps_modif_msg_conf);
  gtk_fixed_put (GTK_FIXED (fixed3), gdps_modif_msg_conf, 16, 448);
  gtk_widget_set_size_request (gdps_modif_msg_conf, 288, 24);

  gdps_modif_label23 = gtk_label_new (_("Conditions Medicales:"));
  gtk_widget_show (gdps_modif_label23);
  gtk_fixed_put (GTK_FIXED (fixed3), gdps_modif_label23, 408, 48);
  gtk_widget_set_size_request (gdps_modif_label23, 216, 25);

  gdps_modif_idetab_sortie = gtk_label_new (_("label13"));
  gtk_widget_show (gdps_modif_idetab_sortie);
  gtk_fixed_put (GTK_FIXED (fixed3), gdps_modif_idetab_sortie, 208, 48);
  gtk_widget_set_size_request (gdps_modif_idetab_sortie, 176, 25);

  gdps_opos_old = gtk_label_new ("");
  gtk_widget_show (gdps_opos_old);
  gtk_fixed_put (GTK_FIXED (fixed3), gdps_opos_old, 256, 160);
  gtk_widget_set_size_request (gdps_opos_old, 48, 24);

  gdps_apos_old = gtk_label_new ("");
  gtk_widget_show (gdps_apos_old);
  gtk_fixed_put (GTK_FIXED (fixed3), gdps_apos_old, 256, 96);
  gtk_widget_set_size_request (gdps_apos_old, 48, 24);

  gdps_bpos_old = gtk_label_new ("");
  gtk_widget_show (gdps_bpos_old);
  gtk_fixed_put (GTK_FIXED (fixed3), gdps_bpos_old, 256, 224);
  gtk_widget_set_size_request (gdps_bpos_old, 48, 24);

  gdps_abpos_old = gtk_label_new ("");
  gtk_widget_show (gdps_abpos_old);
  gtk_fixed_put (GTK_FIXED (fixed3), gdps_abpos_old, 256, 288);
  gtk_widget_set_size_request (gdps_abpos_old, 48, 24);

  gdps_aneg_old = gtk_label_new ("");
  gtk_widget_show (gdps_aneg_old);
  gtk_fixed_put (GTK_FIXED (fixed3), gdps_aneg_old, 352, 96);
  gtk_widget_set_size_request (gdps_aneg_old, 48, 24);

  gdps_oneg_old = gtk_label_new ("");
  gtk_widget_show (gdps_oneg_old);
  gtk_fixed_put (GTK_FIXED (fixed3), gdps_oneg_old, 352, 160);
  gtk_widget_set_size_request (gdps_oneg_old, 48, 24);

  gdps_bneg_old = gtk_label_new ("");
  gtk_widget_show (gdps_bneg_old);
  gtk_fixed_put (GTK_FIXED (fixed3), gdps_bneg_old, 352, 224);
  gtk_widget_set_size_request (gdps_bneg_old, 48, 24);

  gdps_abneg_old = gtk_label_new ("");
  gtk_widget_show (gdps_abneg_old);
  gtk_fixed_put (GTK_FIXED (fixed3), gdps_abneg_old, 352, 288);
  gtk_widget_set_size_request (gdps_abneg_old, 48, 24);

  g_signal_connect ((gpointer) gdps_modifer_button, "clicked",
                    G_CALLBACK (on_gdps_modifer_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) gdps_modif_oui, "toggled",
                    G_CALLBACK (on_gdps_modif_oui_toggled),
                    NULL);
  g_signal_connect ((gpointer) gdps_modif_non, "toggled",
                    G_CALLBACK (on_gdps_modif_non_toggled),
                    NULL);
  g_signal_connect ((gpointer) gdps_modif_choix1, "toggled",
                    G_CALLBACK (on_gdps_modif_choix1_toggled),
                    NULL);
  g_signal_connect ((gpointer) gdps_modif_choix2, "toggled",
                    G_CALLBACK (on_gdps_modif_choix2_toggled),
                    NULL);
  g_signal_connect ((gpointer) gdps_modif_choix4, "toggled",
                    G_CALLBACK (on_gdps_modif_choix4_toggled),
                    NULL);
  g_signal_connect ((gpointer) gdps_modif_choix5, "toggled",
                    G_CALLBACK (on_gdps_modif_choix5_toggled),
                    NULL);
  g_signal_connect ((gpointer) gdps_modif_choix6, "toggled",
                    G_CALLBACK (on_gdps_modif_choix6_toggled),
                    NULL);
  g_signal_connect ((gpointer) gdps_modif_choix7, "toggled",
                    G_CALLBACK (on_gdps_modif_choix7_toggled),
                    NULL);
  g_signal_connect ((gpointer) gdps_modif_choix8, "toggled",
                    G_CALLBACK (on_gdps_modif_choix8_toggled),
                    NULL);
  g_signal_connect ((gpointer) gdps_modif_choix3, "toggled",
                    G_CALLBACK (on_gdps_modif_choix3_toggled),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (fenetre_modifier, fenetre_modifier, "fenetre_modifier");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, gdps_modif_apos, "gdps_modif_apos");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, gdps_modif_aneg, "gdps_modif_aneg");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, gdps_modif_opos, "gdps_modif_opos");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, gdps_modif_oneg, "gdps_modif_oneg");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, gdps_modif_bpos, "gdps_modif_bpos");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, gdps_modif_bneg, "gdps_modif_bneg");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, gdps_modif_abpos, "gdps_modif_abpos");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, gdps_modif_abneg, "gdps_modif_abneg");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, gdps_modif_aneg_label, "gdps_modif_aneg_label");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, gdps_modif_label18, "gdps_modif_label18");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, gdps_modif_label20, "gdps_modif_label20");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, gdps_modif_label22, "gdps_modif_label22");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, gdps_modif_label17, "gdps_modif_label17");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, gdps_modif_label19, "gdps_modif_label19");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, gdps_modif_label21, "gdps_modif_label21");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, gdps_modif_iddem_label, "gdps_modif_iddem_label");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, gdps_modif_idetab_label, "gdps_modif_idetab_label");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, gdps_modi_label14, "gdps_modi_label14");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, hseparator2, "hseparator2");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, gdps_modifer_button, "gdps_modifer_button");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, gdps_modif_iddem_sortie, "gdps_modif_iddem_sortie");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, gdps_modif_oui, "gdps_modif_oui");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, gdps_modif_non, "gdps_modif_non");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, gdps_modif_choix1, "gdps_modif_choix1");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, gdps_modif_choix2, "gdps_modif_choix2");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, gdps_modif_choix4, "gdps_modif_choix4");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, gdps_modif_choix5, "gdps_modif_choix5");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, gdps_modif_choix6, "gdps_modif_choix6");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, gdps_modif_choix7, "gdps_modif_choix7");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, gdps_modif_choix8, "gdps_modif_choix8");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, gdps_modif_label15, "gdps_modif_label15");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, gdps_modif_choix3, "gdps_modif_choix3");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, gdps_modif_label24, "gdps_modif_label24");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, gdps_modif_msg_conf, "gdps_modif_msg_conf");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, gdps_modif_label23, "gdps_modif_label23");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, gdps_modif_idetab_sortie, "gdps_modif_idetab_sortie");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, gdps_opos_old, "gdps_opos_old");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, gdps_apos_old, "gdps_apos_old");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, gdps_bpos_old, "gdps_bpos_old");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, gdps_abpos_old, "gdps_abpos_old");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, gdps_aneg_old, "gdps_aneg_old");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, gdps_oneg_old, "gdps_oneg_old");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, gdps_bneg_old, "gdps_bneg_old");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, gdps_abneg_old, "gdps_abneg_old");

  return fenetre_modifier;
}

