/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_gestion (void);
GtkWidget* create_fenetre_ajouter (void);
GtkWidget* create_fenetre_modifier (void);
GtkWidget* create_authentification (void);
GtkWidget* create_fiche_don_user (void);
GtkWidget* create_aj (void);
GtkWidget* create_mod (void);
GtkWidget* create_af (void);
GtkWidget* create_Statistique (void);
GtkWidget* create_gestionu (void);
GtkWidget* create_ajouteru (void);
GtkWidget* create_affichage (void);
