/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_gestion (void);
GtkWidget* create_fenetre_ajouter (void);
GtkWidget* create_fenetre_modifier (void);
GtkWidget* create_authentification (void);
