/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"
#include "fonctions.h"

int
main (int argc, char *argv[])
{
  GtkWidget *gestion;
  GtkWidget *combobox1;
  chaine* tab;
  int l;



#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  gestion = create_gestion ();
  combobox1 = lookup_widget(gestion, "gdps_choixeatb");

  etab_comb (&l, &tab);
  for (int i = 0; i < l; i++)
  {
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _(tab[i].a));
  }

  gtk_widget_show (gestion);

  gtk_main ();
  return 0;
}

